-- ============================================
-- CineStar Barrio — Creación de Esquemas
-- ============================================
-- Este script se ejecuta como SYSTEM en XEPDB1
-- Crea los dos esquemas requeridos (RST-02)

ALTER SESSION SET CONTAINER = XEPDB1;

-- ─── Esquema Operativo/Transaccional ───
-- El usuario APP_USER (CINESTAR_OPS) ya es creado por la imagen Docker
-- Le otorgamos permisos adicionales
GRANT CREATE TABLE TO CINESTAR_OPS;
GRANT CREATE SEQUENCE TO CINESTAR_OPS;
GRANT CREATE PROCEDURE TO CINESTAR_OPS;
GRANT CREATE TRIGGER TO CINESTAR_OPS;
GRANT CREATE VIEW TO CINESTAR_OPS;
GRANT CREATE SESSION TO CINESTAR_OPS;
GRANT UNLIMITED TABLESPACE TO CINESTAR_OPS;

-- ─── Esquema Administrativo/Auditoría ───
CREATE USER CINESTAR_ADMIN IDENTIFIED BY "AdminPass2024!";
GRANT CREATE TABLE TO CINESTAR_ADMIN;
GRANT CREATE SEQUENCE TO CINESTAR_ADMIN;
GRANT CREATE VIEW TO CINESTAR_ADMIN;
GRANT CREATE SESSION TO CINESTAR_ADMIN;
GRANT CREATE PROCEDURE TO CINESTAR_ADMIN;
GRANT UNLIMITED TABLESPACE TO CINESTAR_ADMIN;

COMMIT;
