-- ============================================
-- CineStar Barrio — Tablas Operativas
-- Esquema: CINESTAR_OPS
-- ============================================

ALTER SESSION SET CONTAINER = XEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = CINESTAR_OPS;

-- ─── Secuencias ───
CREATE SEQUENCE SEQ_PELICULAS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_SALAS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ASIENTOS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_FUNCIONES START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_RESERVAS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_RESERVA_ASIENTOS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_USUARIOS START WITH 1 INCREMENT BY 1;

-- ─── USUARIOS ───
CREATE TABLE USUARIOS (
    ID              NUMBER DEFAULT SEQ_USUARIOS.NEXTVAL PRIMARY KEY,
    USERNAME        VARCHAR2(50)  NOT NULL UNIQUE,
    PASSWORD_HASH   VARCHAR2(255) NOT NULL,
    NOMBRE_COMPLETO VARCHAR2(150) NOT NULL,
    ROL             VARCHAR2(20)  NOT NULL CHECK (ROL IN ('ADMIN', 'OPERADOR')),
    ACTIVO          NUMBER(1)     DEFAULT 1 NOT NULL CHECK (ACTIVO IN (0, 1)),
    FECHA_CREACION  TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    FECHA_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ─── PELICULAS ───
CREATE TABLE PELICULAS (
    ID             NUMBER DEFAULT SEQ_PELICULAS.NEXTVAL PRIMARY KEY,
    TITULO         VARCHAR2(200) NOT NULL,
    DURACION_MIN   NUMBER        NOT NULL CHECK (DURACION_MIN > 0),
    CLASIFICACION  VARCHAR2(10)  NOT NULL CHECK (CLASIFICACION IN ('G', 'PG', 'PG-13', 'R', 'NC-17', 'TE', 'TP', 'A', 'B', 'B15', 'C', 'D')),
    SINOPSIS       CLOB,
    GENERO         VARCHAR2(50)  NOT NULL,
    POSTER_URL     VARCHAR2(500),
    ACTIVO         NUMBER(1)     DEFAULT 1 NOT NULL CHECK (ACTIVO IN (0, 1)),
    FECHA_CREACION TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
);

-- ─── SALAS ───
CREATE TABLE SALAS (
    ID             NUMBER DEFAULT SEQ_SALAS.NEXTVAL PRIMARY KEY,
    NOMBRE         VARCHAR2(50)  NOT NULL UNIQUE,
    CAPACIDAD      NUMBER        NOT NULL CHECK (CAPACIDAD > 0),
    ACTIVO         NUMBER(1)     DEFAULT 1 NOT NULL CHECK (ACTIVO IN (0, 1)),
    FECHA_CREACION TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
);

-- ─── ASIENTOS ───
CREATE TABLE ASIENTOS (
    ID          NUMBER DEFAULT SEQ_ASIENTOS.NEXTVAL PRIMARY KEY,
    SALA_ID     NUMBER       NOT NULL REFERENCES SALAS(ID),
    FILA        VARCHAR2(2)  NOT NULL,
    NUMERO      NUMBER       NOT NULL CHECK (NUMERO > 0),
    TIPO        VARCHAR2(20) DEFAULT 'NORMAL' NOT NULL CHECK (TIPO IN ('NORMAL', 'SILLA_RUEDAS')),
    SECCION     VARCHAR2(20) DEFAULT 'PRINCIPAL' NOT NULL CHECK (SECCION IN ('PRINCIPAL', 'LATERAL')),
    ACTIVO      NUMBER(1)    DEFAULT 1 NOT NULL CHECK (ACTIVO IN (0, 1)),
    CONSTRAINT UK_ASIENTO_SALA UNIQUE (SALA_ID, FILA, NUMERO)
);

CREATE INDEX IDX_ASIENTOS_SALA ON ASIENTOS(SALA_ID);

-- ─── FUNCIONES ───
CREATE TABLE FUNCIONES (
    ID             NUMBER DEFAULT SEQ_FUNCIONES.NEXTVAL PRIMARY KEY,
    PELICULA_ID    NUMBER    NOT NULL REFERENCES PELICULAS(ID),
    SALA_ID        NUMBER    NOT NULL REFERENCES SALAS(ID),
    FECHA          DATE      NOT NULL,
    HORA_INICIO    TIMESTAMP NOT NULL,
    HORA_FIN       TIMESTAMP NOT NULL,
    PRECIO         NUMBER(10,2) NOT NULL CHECK (PRECIO >= 0),
    ESTADO         VARCHAR2(20) DEFAULT 'PROGRAMADA' NOT NULL CHECK (ESTADO IN ('PROGRAMADA', 'EN_CURSO', 'FINALIZADA', 'CANCELADA')),
    FECHA_CREACION TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT CHK_HORA CHECK (HORA_FIN > HORA_INICIO)
);

CREATE INDEX IDX_FUNCIONES_SALA_FECHA ON FUNCIONES(SALA_ID, FECHA);
CREATE INDEX IDX_FUNCIONES_PELICULA ON FUNCIONES(PELICULA_ID);

-- ─── RESERVAS ───
CREATE TABLE RESERVAS (
    ID             NUMBER DEFAULT SEQ_RESERVAS.NEXTVAL PRIMARY KEY,
    FUNCION_ID     NUMBER       NOT NULL REFERENCES FUNCIONES(ID),
    USUARIO_ID     NUMBER       NOT NULL REFERENCES USUARIOS(ID),
    CODIGO_BOLETO  VARCHAR2(20) NOT NULL UNIQUE,
    NOMBRE_CLIENTE VARCHAR2(150) NOT NULL,
    TELEFONO_CLIENTE VARCHAR2(20),
    CANAL          VARCHAR2(20) NOT NULL CHECK (CANAL IN ('TAQUILLA', 'TELEFONICA')),
    ESTADO         VARCHAR2(20) DEFAULT 'RESERVADA' NOT NULL CHECK (ESTADO IN ('RESERVADA', 'VENDIDA', 'CANCELADA')),
    FECHA_RESERVA  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    FECHA_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_RESERVAS_FUNCION ON RESERVAS(FUNCION_ID);
CREATE INDEX IDX_RESERVAS_CODIGO ON RESERVAS(CODIGO_BOLETO);
CREATE INDEX IDX_RESERVAS_USUARIO ON RESERVAS(USUARIO_ID);

-- ─── RESERVA_ASIENTOS (relación reserva ↔ asientos) ───
CREATE TABLE RESERVA_ASIENTOS (
    ID          NUMBER DEFAULT SEQ_RESERVA_ASIENTOS.NEXTVAL PRIMARY KEY,
    RESERVA_ID  NUMBER NOT NULL REFERENCES RESERVAS(ID),
    ASIENTO_ID  NUMBER NOT NULL REFERENCES ASIENTOS(ID),
    FUNCION_ID  NUMBER NOT NULL REFERENCES FUNCIONES(ID),
    ESTADO      VARCHAR2(20) DEFAULT 'OCUPADO' NOT NULL CHECK (ESTADO IN ('OCUPADO', 'LIBERADO')),
    CONSTRAINT UK_ASIENTO_FUNCION UNIQUE (ASIENTO_ID, FUNCION_ID, ESTADO)
);

CREATE INDEX IDX_RA_RESERVA ON RESERVA_ASIENTOS(RESERVA_ID);
CREATE INDEX IDX_RA_FUNCION ON RESERVA_ASIENTOS(FUNCION_ID);
CREATE INDEX IDX_RA_ASIENTO ON RESERVA_ASIENTOS(ASIENTO_ID);

COMMIT;
