-- ============================================
-- CineStar Barrio — Tablas de Auditoría/Reportes
-- Esquema: CINESTAR_ADMIN
-- ============================================

ALTER SESSION SET CONTAINER = XEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = CINESTAR_ADMIN;

-- ─── Secuencias ───
CREATE SEQUENCE SEQ_LOG_OPERACIONES START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CANCELACIONES START WITH 1 INCREMENT BY 1;

-- ─── LOG DE OPERACIONES (RF-14) ───
CREATE TABLE LOG_OPERACIONES (
    ID              NUMBER DEFAULT SEQ_LOG_OPERACIONES.NEXTVAL PRIMARY KEY,
    OPERACION       VARCHAR2(50)  NOT NULL,
    TABLA_AFECTADA  VARCHAR2(50)  NOT NULL,
    REGISTRO_ID     NUMBER,
    USUARIO_ID      NUMBER,
    USUARIO_NOMBRE  VARCHAR2(50),
    DETALLES        CLOB,
    FECHA_HORA      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IDX_LOG_FECHA ON LOG_OPERACIONES(FECHA_HORA);
CREATE INDEX IDX_LOG_OPERACION ON LOG_OPERACIONES(OPERACION);
CREATE INDEX IDX_LOG_USUARIO ON LOG_OPERACIONES(USUARIO_ID);

-- ─── CANCELACIONES (RF-12) ───
CREATE TABLE CANCELACIONES (
    ID              NUMBER DEFAULT SEQ_CANCELACIONES.NEXTVAL PRIMARY KEY,
    RESERVA_ID      NUMBER        NOT NULL,
    CODIGO_BOLETO   VARCHAR2(20)  NOT NULL,
    FUNCION_ID      NUMBER        NOT NULL,
    USUARIO_ID      NUMBER        NOT NULL,
    USUARIO_NOMBRE  VARCHAR2(50)  NOT NULL,
    NOMBRE_CLIENTE  VARCHAR2(150),
    ASIENTOS_LIBERADOS VARCHAR2(500),
    MOTIVO          VARCHAR2(500),
    FECHA_HORA      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IDX_CANCEL_FECHA ON CANCELACIONES(FECHA_HORA);
CREATE INDEX IDX_CANCEL_RESERVA ON CANCELACIONES(RESERVA_ID);
CREATE INDEX IDX_CANCEL_USUARIO ON CANCELACIONES(USUARIO_ID);

COMMIT;
