-- ============================================
-- CineStar Barrio — Permisos entre Esquemas
-- (RF-13) Acceso restringido según perfil/rol
-- ============================================

ALTER SESSION SET CONTAINER = XEPDB1;

-- ─── CINESTAR_OPS puede insertar logs en CINESTAR_ADMIN ───
GRANT INSERT ON CINESTAR_ADMIN.LOG_OPERACIONES TO CINESTAR_OPS;
GRANT INSERT ON CINESTAR_ADMIN.CANCELACIONES TO CINESTAR_OPS;
GRANT SELECT ON CINESTAR_ADMIN.SEQ_LOG_OPERACIONES TO CINESTAR_OPS;
GRANT SELECT ON CINESTAR_ADMIN.SEQ_CANCELACIONES TO CINESTAR_OPS;

-- ─── CINESTAR_ADMIN puede leer tablas operativas (solo lectura) ───
GRANT SELECT ON CINESTAR_OPS.PELICULAS TO CINESTAR_ADMIN;
GRANT SELECT ON CINESTAR_OPS.SALAS TO CINESTAR_ADMIN;
GRANT SELECT ON CINESTAR_OPS.ASIENTOS TO CINESTAR_ADMIN;
GRANT SELECT ON CINESTAR_OPS.FUNCIONES TO CINESTAR_ADMIN;
GRANT SELECT ON CINESTAR_OPS.RESERVAS TO CINESTAR_ADMIN;
GRANT SELECT ON CINESTAR_OPS.RESERVA_ASIENTOS TO CINESTAR_ADMIN;
GRANT SELECT ON CINESTAR_OPS.USUARIOS TO CINESTAR_ADMIN;

COMMIT;
